// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/c/[slug]" | "/clubs" | "/clubs/[id]" | "/docs" | "/events" | "/invite/[token]" | "/live/[...token]" | "/login" | "/profile" | "/register" | "/score" | "/score/[matchId]" | "/shop" | "/stats"
type PageRoutes = never
type LayoutRoutes = "/" | "/live/[...token]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/c/[slug]": { "slug": string; }
  "/clubs": {}
  "/clubs/[id]": { "id": string; }
  "/docs": {}
  "/events": {}
  "/invite/[token]": { "token": string; }
  "/live/[...token]": { "token": string[]; }
  "/login": {}
  "/profile": {}
  "/register": {}
  "/score": {}
  "/score/[matchId]": { "matchId": string; }
  "/shop": {}
  "/stats": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/live/[...token]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
