apiVersion: v1
kind: Service
metadata:
  name: {{ include "fishers-postgres.name" . }}
  labels:
    {{- include "fishers-postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: postgres
  selector:
    {{- include "fishers-postgres.selectorLabels" . | nindent 4 }}
