apiVersion: v1
kind: Service
metadata:
  name: {{ include "fishers-minio.name" . }}
  labels:
    {{- include "fishers-minio.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: s3
      port: {{ .Values.service.port }}
      targetPort: s3
    - name: console
      port: {{ .Values.service.consolePort }}
      targetPort: console
  selector:
    {{- include "fishers-minio.selectorLabels" . | nindent 4 }}
